= Roseau Gradle Plugin

image:https://img.shields.io/github/commits-since/rahulsom/roseau-plugin/latest?style=for-the-badge[GitHub commits since latest release, link="https://github.com/rahulsom/roseau-plugin/releases/new"]

This is a Gradle plugin for https://github.com/alien-tools/roseau[Roseau].
Roseau computes differences between two versions of a software project and generates a report of the changes.

== Setup

image:https://img.shields.io/gradle-plugin-portal/v/io.github.rahulsom.roseau?style=for-the-badge[Gradle Plugin Portal, link="https://plugins.gradle.org/plugin/io.github.rahulsom.roseau"]

In your `build.gradle.kts` file, add the following to the `plugins` block:

[source,kotlin]
----
plugins {
    id("io.github.rahulsom.roseau").version("<INSERT VERSION HERE>") // <1>
}
----
<1> Version is optional.

== Usage

Run this command.

[source,sh]
----
./gradlew roseau
----

This will use your configured `repositories` to find the `latest.release` for your project.
Then it will compute the differences between the current version and the latest release and generate a report in `build/reports/roseau`.

By default, it will generate all formats of reports that roseau supports.

* HTML
* JSON
* Markdown
* CSV
* CLI Output

You can turn these off individually by setting these properties in your `build.gradle.kts` file.

[source,kotlin]
----
roseau {
    html.set(false)
    json.set(false)
    md.set(false)
    csv.set(false)
    cli.set(false)
}
----

You can also configure the `roseau` version to use.

[source,kotlin]
----
roseau {
    version.set("0.6.0") // <1>
}
----
<1> This is set to a version that is compatible with the plugin by default.

You can choose the verbosity of the output.

[source,kotlin]
----
import com.github.rahulsom.RoseauExtension

roseau {
    verbosity.set(RoseauExtension.VerbosityLevel.NONE) // <1>
}
----

<1> Verbosity levels are `NONE`, `SOME`, and `VERBOSE`.